[package]
name = "royal-son"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
rand = "0.8.4"

[workspace]
members = ["actix-server", "yew-app"]
default-members = ["actix-server"]
